periodics:
  - interval: 12h
    name: periodic-jobset-test-unit-release-0-7
    cluster: eks-prow-build-cluster
    extra_refs:
      - org: kubernetes-sigs
        repo: jobset
        base_ref: release-0.7
        path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-jobset-test-unit-release-0-7
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic jobset unit tests on release 0.7"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241021-d3a4913879-master
        env:
        - name: GO_TEST_FLAGS
          value: "-race -count 3"
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - test
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 3
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
  - interval: 12h
    name: periodic-jobset-test-integration-release-0-7
    cluster: eks-prow-build-cluster
    extra_refs:
      - org: kubernetes-sigs
        repo: jobset
        base_ref: release-0.7
        path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-jobset-test-integration-release-0-7
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic jobset integration tests on release 0.7"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
    decorate: true
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.22
        command:
        - make
        args:
        - test-integration
        resources:
          limits:
            cpu: 3
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
  - interval: 12h
    name: periodic-jobset-test-e2e-release-0-7-1-28
    cluster: eks-prow-build-cluster
    extra_refs:
      - org: kubernetes-sigs
        repo: jobset
        base_ref: release-0.7
        path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-jobset-test-e2e-release-0-7-1-28
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic jobset end to end tests for Kubernetes 1.28 on release 0.7"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241021-d3a4913879-master
        env:
        - name: E2E_KIND_VERSION
          value: kindest/node:v1.28.9
        - name: BUILDER_IMAGE
          value: public.ecr.aws/docker/library/golang:1.22
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - test-e2e-kind
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 3
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
  - interval: 12h
    name: periodic-jobset-test-e2e-release-0-7-1-29
    cluster: eks-prow-build-cluster
    extra_refs:
      - org: kubernetes-sigs
        repo: jobset
        base_ref: release-0.7
        path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-jobset-test-e2e-release-0-5-1-29
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic jobset end to end tests for Kubernetes 1.29 on release 0.7"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241021-d3a4913879-master
        env:
        - name: E2E_KIND_VERSION
          value: kindest/node:v1.29.0
        - name: BUILDER_IMAGE
          value: public.ecr.aws/docker/library/golang:1.22
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - test-e2e-kind
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 3
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
