dashboards:
- dashboard_tab:
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.17-lp-rosa-classic-amq-streams-2-7-rosa-aws
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.17-lp-rosa-classic-amq-streams-2-7-rosa-aws
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.17-lp-rosa-classic-servicemesh-rosa-aws
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.17-lp-rosa-classic-servicemesh-rosa-aws
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.17-lp-rosa-classic-openshift-pipelines-interop-rosa-aws
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.17-lp-rosa-classic-openshift-pipelines-interop-rosa-aws
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-rosa-classic-devspaces-rosa-aws
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-rosa-classic-devspaces-rosa-aws
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.17-lp-rosa-classic-web-terminal-rosa-aws
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.17-lp-rosa-classic-web-terminal-rosa-aws
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-rh-messaging-qe-claire-amq-broker-lpt-amq-broker-ocp4.17-lp-rosa-classic-amq-broker-rosa-aws
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-rh-messaging-qe-claire-amq-broker-lpt-amq-broker-ocp4.17-lp-rosa-classic-amq-broker-rosa-aws
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-classic-rhsso-interop-aws
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-classic-rhsso-interop-aws
  name: redhat-openshift-lp-rosa-classic-release-4.17-informing
test_groups:
- gcs_prefix: test-platform-results/logs/periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.17-lp-rosa-classic-amq-streams-2-7-rosa-aws
  name: periodic-ci-amq-streams-qe-strimzi-kafka-operator-main-amq-streams-ocp4.17-lp-rosa-classic-amq-streams-2-7-rosa-aws
- gcs_prefix: test-platform-results/logs/periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.17-lp-rosa-classic-servicemesh-rosa-aws
  name: periodic-ci-maistra-maistra-test-tool-main-servicemesh-ocp4.17-lp-rosa-classic-servicemesh-rosa-aws
- gcs_prefix: test-platform-results/logs/periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.17-lp-rosa-classic-openshift-pipelines-interop-rosa-aws
  name: periodic-ci-openshift-pipelines-release-tests-release-v1.16-openshift-pipelines-ocp4.17-lp-rosa-classic-openshift-pipelines-interop-rosa-aws
- gcs_prefix: test-platform-results/logs/periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-rosa-classic-devspaces-rosa-aws
  name: periodic-ci-redhat-developer-devspaces-interop-tests-main-devspaces-ocp4.17-lp-rosa-classic-devspaces-rosa-aws
- gcs_prefix: test-platform-results/logs/periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.17-lp-rosa-classic-web-terminal-rosa-aws
  name: periodic-ci-redhat-developer-web-terminal-operator-main-web-terminal-ocp4.17-lp-rosa-classic-web-terminal-rosa-aws
- gcs_prefix: test-platform-results/logs/periodic-ci-rh-messaging-qe-claire-amq-broker-lpt-amq-broker-ocp4.17-lp-rosa-classic-amq-broker-rosa-aws
  name: periodic-ci-rh-messaging-qe-claire-amq-broker-lpt-amq-broker-ocp4.17-lp-rosa-classic-amq-broker-rosa-aws
- gcs_prefix: test-platform-results/logs/periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-classic-rhsso-interop-aws
  name: periodic-ci-rhbk-sso-test-main-rhsso-product-ocp4.17-lp-rosa-classic-rhsso-interop-aws
