presubmits:
  kubernetes/ingress-nginx:
    # Ingress NGINX: Boilerplate
    - name: pre-ingress-nginx-boilerplate
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        testgrid-dashboards: sig-network-ingress-nginx
        testgrid-tab-name: boilerplate
      run_if_changed: \.(go|sh)$
      cluster: eks-prow-build-cluster
      decorate: true
      path_alias: k8s.io/ingress-nginx
      spec:
        containers:
          - image: registry.k8s.io/ingress-nginx/e2e-test-runner:v20241004-114a6abb@sha256:1389ec0589abbf5c431c9290c4c307437c8396995c63dda5eac26abd70963dc8
            command:
              - hack/verify-boilerplate.sh
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 2
                memory: 4Gi

    # Ingress NGINX: CodeGen
    - name: pre-ingress-nginx-codegen
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        testgrid-dashboards: sig-network-ingress-nginx
        testgrid-tab-name: codegen
      run_if_changed: \.go$
      cluster: eks-prow-build-cluster
      decorate: true
      path_alias: k8s.io/ingress-nginx
      spec:
        containers:
          - image: registry.k8s.io/ingress-nginx/e2e-test-runner:v20241004-114a6abb@sha256:1389ec0589abbf5c431c9290c4c307437c8396995c63dda5eac26abd70963dc8
            command:
              - hack/verify-codegen.sh
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 2
                memory: 4Gi

    # Ingress NGINX: Lua Test
    - name: pre-ingress-nginx-lua-test
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
      annotations:
        testgrid-dashboards: sig-network-ingress-nginx
        testgrid-tab-name: lua-test
      run_if_changed: \.lua$
      cluster: eks-prow-build-cluster
      decorate: true
      path_alias: k8s.io/ingress-nginx
      spec:
        containers:
          - image: registry.k8s.io/ingress-nginx/e2e-test-runner:v20241004-114a6abb@sha256:1389ec0589abbf5c431c9290c4c307437c8396995c63dda5eac26abd70963dc8
            command:
              - make
            args:
              - lua-test
            resources:
              requests:
                cpu: 2
                memory: 4Gi
              limits:
                cpu: 2
                memory: 4Gi
