presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-kind-dra-timeout
    cluster: eks-prow-build-cluster
    skip_branches:
    - release-\d+\.\d+  # per-release image
    always_run: false
    optional: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    annotations:
      testgrid-dashboards: sig-node-dynamic-resource-allocation
      description: Runs E2E tests for Dynamic Resource Allocation beta features against a Kubernetes master cluster created with sigs.k8s.io/kind, using a 15min timeout
    decorate: true
    decoration_config:
      timeout: 15 # artificially low to test timeout handling
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241230-3006692a6f-master
        command:
        - runner.sh
        args:
        - /bin/bash
        - -xce
        - |
          make WHAT="github.com/onsi/ginkgo/v2/ginkgo k8s.io/kubernetes/test/e2e/e2e.test"
          curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" kind
          kind build node-image --image=dra/node:latest .
          trap 'kind export logs "${ARTIFACTS}/kind"; kind delete cluster' EXIT
          kind create cluster --retain --config test/e2e/dra/kind.yaml --image dra/node:latest
          KUBERNETES_PROVIDER=local KUBECONFIG=${HOME}/.kube/config GINKGO_PARALLEL_NODES=8 E2E_REPORT_DIR=${ARTIFACTS} GINKGO_TIMEOUT=2h30m hack/ginkgo-e2e.sh -ginkgo.label-filter='Feature: containsAny DynamicResourceAllocation && Feature: isSubsetOf { Beta, DynamicResourceAllocation } && !Flaky'
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 2
            memory: 9Gi
          requests:
            cpu: 2
            memory: 9Gi

  - name: pull-kubernetes-node-e2e-crio-cgrpv1-dra-timeout
    cluster: k8s-infra-prow-build
    skip_branches:
    - release-\d+\.\d+  # per-release image
    always_run: false
    optional: true
    skip_report: false
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    annotations:
      testgrid-dashboards: sig-node-dynamic-resource-allocation
      description: Runs E2E node tests for Dynamic Resource Allocation beta features with CRI-O using cgroup v1, using a 15 min timeout
    decorate: true
    decoration_config:
      timeout: 15m # artificially low to test timeout handling
    path_alias: k8s.io/kubernetes
    extra_refs:
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241230-3006692a6f-master
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --deployment=node
        - --env=KUBE_SSH_USER=core
        - --gcp-zone=us-west1-b
        - '--node-test-args=--feature-gates=DynamicResourceAllocation=true --service-feature-gates=DynamicResourceAllocation=true --runtime-config=api/beta=true --container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
        - --node-tests=true
        - --provider=gce
        - '--test_args=--timeout=1h --label-filter="Feature: containsAny DynamicResourceAllocation && Feature: isSubsetOf { Beta, DynamicResourceAllocation } && !Flaky && !Slow"'
        - --timeout=65m
        - --node-args=--image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/crio/latest/image-config-cgroupv1-serial.yaml
        env:
        - name: IGNITION_INJECT_GCE_SSH_PUBLIC_KEY_FILE
          value: "1"
        - name: GOPATH
          value: /go
        resources:
          limits:
            cpu: 2
            memory: 9Gi
          requests:
            cpu: 2
            memory: 9Gi
