presubmits:
  kubernetes-sigs/container-object-storage-interface:
  - name: pull-container-object-storage-interface-build
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/container-object-storage-interface
    annotations:
      testgrid-dashboards: sig-storage-container-object-storage-interface
      testgrid-tab-name: build
      description: Build test in container-object-storage-interface repo.
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241230-3006692a6f-master
        command:
        - runner.sh
        args:
        - make
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi

  - name: pull-container-object-storage-interface-unit
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/container-object-storage-interface
    annotations:
      testgrid-dashboards: sig-storage-container-object-storage-interface
      testgrid-tab-name: unit
      description: Unit tests in container-object-storage-interface repo.
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241230-3006692a6f-master
        command:
        - runner.sh
        args:
        - make
        - test
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
