postsubmits:
  etcd-io/etcd:
  - name: post-etcd-build
    cluster: eks-prow-build-cluster
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-postsubmits
      testgrid-tab-name: post-etcd-build
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20241021-d3a4913879-master
        command:
        - runner.sh
        args:
        - make
        - build
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "4Gi"
