---
presubmits:
  etcd-io/raft:
    - name: pull-raft-test-arm64
      cluster: k8s-infra-prow-build
      always_run: true
      branches:
        - main
      decorate: true
      annotations:
        testgrid-dashboards: sig-etcd-raft-presubmits
        testgrid-tab-name: pull-raft-test-arm64
      spec:
        containers:
          - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20241021-d3a4913879-master
            command:
              - runner.sh
            args:
              - bash
              - -c
              - |
                GOARCH=arm64 PASSES='unit' RACE='true' CPU='4' ./scripts/test.sh -p=2
            resources:
              requests:
                cpu: "4"
                memory: "4Gi"
              limits:
                cpu: "4"
                memory: "4Gi"
